# zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="afowler"
DISABLE_AUTO_TITLE="true"
plugins=(mercurial)
source $ZSH/oh-my-zsh.sh
~/.vim/bundle/gruvbox/gruvbox_256palette.sh
~/.vim/bundle/gruvbox/gruvbox_256palette_osx.sh

function git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$ZSH_THEME_GIT_PROMPT_SUFFIX"
}

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# devie
export DEVIE_PATH="$HOME/.devie"
export PATH="$PATH:$DEVIE_PATH"

# gitenv 
if [ -f $HOME/.gitenv ]; then
  source $HOME/.gitenv
else
  echo "WARNING: not logged in, please run 'set-gitenv' script"
fi

# exercism
export PATH="$HOME/.exercism:$PATH"

# rubygems
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

#rbenv
if hash rbenv 2>/dev/null; then
  eval "$(rbenv init -)"
fi

# go
export GOPATH="$HOME/go"
export PATH="$HOME/go/bin:$PATH"

# tmuxinator
export EDITOR="vim"

# heroku
export PATH="/usr/local/heroku/bin:$PATH"

# cabal
export PATH="$HOME/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.4/bin:$PATH"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -l -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Postgres.app on OSX
export PATH="/Applications/Postgres.app/Contents/Versions/9.4/bin:$PATH"

# ssh-agent
keychain $HOME/.ssh/id_rsa

# alias
alias fit="git reset --hard"
alias peace="sudo poweroff"
alias .1="cd ../"
alias .2="cd ../../"
alias .3="cd ../../../"
alias .4="cd ../../../../"
alias be="bundle exec"
alias moo="bundle exec rake db:migrate"
alias anni="bundle exec annotate --exclude tests,fixtures,factories"
alias gi="git"
alias t="git status"
alias b="bundle"
alias z!="source ~/.zshrc"
alias v="vagrant"
alias booya="vagrant up && vagrant ssh"
alias ha="habitica"

