---

- name: RG - Ubuntu - Install
  command: "curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb && sudo dpkg -i ripgrep_0.10.0_amd64.deb"
  when: ansible_distribution == 'Ubuntu'

- name: RG - MacOSX - Install ripgrep with Homebrew
  homebrew: name=ripgrep
    state=latest
  when: ansible_distribution == 'MacOSX'
