---

- name: VIM - Ubuntu - Add Vim8 repository
  become: yes
  become_method: 'sudo'
  apt_repository:
    repo: "ppa:jonathonf/vim"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: VIM - Ubuntu - Install vim with Apt
  become: yes
  become_method: 'sudo'
  apt: name=vim state=latest update_cache=yes cache_valid_time=43200
  when: ansible_distribution == 'Ubuntu'

- name: VIM - MacOSX - Install vim with Homebrew
  homebrew: name=vim
    state=latest
  when: ansible_distribution == 'MacOSX'

- name: VIM - MacOSX - Install nvim with Homebrew
  homebrew: name=nvim
    state=latest
  when: ansible_distribution == 'MacOSX'

- name: VIM - Symlink vimrc
  file:
    src: ~/.devenv/roles/editor/files/vimrc
    dest: ~/.vimrc
    state: link
    force: true
  tags:
    - dotfile

- name: NVIM - create nvim config dir
  file: path=~/.config/nvim
        state=directory
        mode=0755

- name: NVIM - Symlink nvim/init.vim
  file:
    src: ~/.devenv/roles/editor/files/vimrc
    dest: ~/.config/nvim/init.vim
    state: link
    force: true
  tags:
    - dotfile

- name: NVIM - OSX - pip tools for nvim
  shell: pip install setuptools && pip  install --upgrade neovim && pip2 install --upgrade neovim && pip3 install --upgrade neovim
  when: ansible_distribution == 'MacOSX'


