---

- name: VIM - Ubuntu - Add Vim8 repository
  become: yes
  become_method: 'sudo'
  apt_repository:
    repo: "ppa:jonathonf/vim"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: VIM - Ubuntu - Install vim with Apt
  become: yes
  become_method: 'sudo'
  apt: name=vim state=latest update_cache=yes cache_valid_time=43200
  when: ansible_distribution == 'Ubuntu'

- name: VIM - MacOSX - Install vim with Homebrew
  homebrew: name=vim
    state=latest
  when: ansible_distribution == 'MacOSX'

- name: VIM - MacOSX - Install nvim with Homebrew
  homebrew: name=nvim
    state=latest
  when: ansible_distribution == 'MacOSX'

- name: VIM - Symlink vimrc
  copy: src=vimrc
        dest=~/.vimrc
  tags:
    - dotfile

- name: VIM - create nvim config dir
  file: path=~/.config/nvim
        state=directory
        mode=0755

- name: VIM - Symlink nvim/init.vim
  copy: src=vimrc
        dest=~/.config/nvim/init.vim

