- name: Install Exercism
  raw: curl -fsSL https://raw.githubusercontent.com/exercism/cli-www/master/public/install | bash 

- name: Clone FZF
  git: repo=https://github.com/junegunn/fzf.git 
       dest=~/.fzf

- name: Install FZF
  raw: ~/.fzf/install   

- name: Clone Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git 
       dest=~/.vim/bundle/Vundle.vim

- script: username
  register: username_results

- name: Install/update VIM plugins
  become: yes
  become_method: sudo
  become_user: '{{username_results.stdout_lines[0]}}'
  command: vim +BundleInstall +qall

- name: Install oh-my-zsh
  become: yes
  become_method: sudo
  become_user: '{{username_results.stdout_lines[0]}}'
  command: curl -fslL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

