- name: Exercism 
  raw: curl -fsSL https://raw.githubusercontent.com/exercism/cli-www/master/public/install | bash 

- name: FZF - Clone github repository to `$HOME/.fzf`
  git: repo=https://github.com/junegunn/fzf.git 
       dest=~/.fzf

- name: FZF - Run install script from cloned repository.
  shell: ~/.fzf/install --all
  register: fzf_install
  changed_when: "fzf_install.stdout | search('Added')"

- name: Vim Plug - .vim/autoload directory is present
  file: path=~/.vim/autoload
        state=directory

- name: Vim Plug - run install
  shell: vim +PlugInstall +qall
  register: vim_plug_install
  changed_when: "vim_plug_install.stdout | search('continue')"

- name: Antigen - Clone github repository to `$HOME/.antigen`
  git:
    repo=https://github.com/zsh-users/antigen
    dest=~/.antigen

- name: TPM - Clone github repository to `$HOME/.tmux/plugins/tpm`
  git:
    repo=https://github.com/tmux-plugins/tpm
    dest=~/.tmux/plugins/tpm
