- name: Install Exercism by piping to bash the result of a curl command to exercism's github repository.
  raw: curl -fsSL https://raw.githubusercontent.com/exercism/cli-www/master/public/install | bash 

- name: Clone FZF github repository to `$HOME/.fzf`
  git: repo=https://github.com/junegunn/fzf.git 
       dest=~/.fzf

- name: Run FZF install script from cloned repository.
  raw: ~/.fzf/install   

- name: Clone Vim Plug github repository to `$HOME/.vim-plug`
  git: repo=https://github.com/junegunn/vim-plug
       dest=~/.vim-plug/

- name: .vim/autoload directory is present
  file: path=~/.vim/autoload
        state=directory

- name: Link vim.plug to .vim/autoload directory
  template: 
    src: ~/.vim-plug/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: update vim plugins by running :PlugInstall command outside of the editor
  command: vim +PluginInstall! +qall
  changed_when: false

- name: TRAVIS-CI WORKAROUND. Next two tasks need to assume sudo to run correctly on travis. run the custom username script and save result in the username_result register.  This will be used as the sudo user later.
  script: username
  register: username_results
  changed_when: false

- name: Install oh-my-zsh by piping to bash the result of a curl command to oh-my-zsh's github repository.
  become: yes
  become_method: sudo
  become_user: '{{username_results.stdout_lines[0]}}'
  raw: curl -fslL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

