- name: Exercism - Install by piping to bash the result of a curl command to exercism's github repository.
  raw: curl -fsSL https://raw.githubusercontent.com/exercism/cli-www/master/public/install | bash 

- name: FZF - Clone FZF github repository to `$HOME/.fzf`
  git: repo=https://github.com/junegunn/fzf.git 
       dest=~/.fzf

- name: FZF - Run FZF install script from cloned repository.
  raw: ~/.fzf/install   

- name: Vim Plug - Clone github repository to `$HOME/.vim-plug`
  git: repo=https://github.com/junegunn/vim-plug
       dest=~/.vim-plug/

- name: Vim Plug - .vim/autoload directory is present
  file: path=~/.vim/autoload
        state=directory

- name: Vim Plug - Link vim.plug to .vim/autoload directory
  template: 
    src: ~/.vim-plug/plug.vim
    dest: ~/.vim/autoload/plug.vim

- include_vars: vim_packages.yml

- name: Install Vim Libraries
  git: repo=https://github.com/{{item.user}}/{{item.repo}}
       dest=~/.vim/plugged/{{item.repo}}
  with_items: "{{ vim_packages }}"

# Coppied from veggiemonk/anisble-ohmyzsh
# - name: Backing up existing ~/.zshrc
#   shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
#   when: installation|success
#   sudo: no

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success

