- name: Install Exercism
  raw: curl -fsSL https://raw.githubusercontent.com/exercism/cli-www/master/public/install | bash 

- name: Clone FZF
  git: repo=https://github.com/junegunn/fzf.git 
       dest=~/.fzf

- name: Install FZF
  raw: ~/.fzf/install   

- name: Clone Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git 
       dest=~/.vim/bundle/Vundle.vim

# - name: Install/update VIM plugins
#   raw: vim +BundleInstall +qall
#   when: travis_on_the_host != "travis"

- name: Install/update VIM plugins TRAVIS STYLE
  # become: yes
  # become_method: sudo
  shell: vim +BundleInstall +qall
  # when: travis_on_the_host == "travis"

# - name: Install oh-my-zsh
#   raw: echo "her we goooo" && curl -fslL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
#   when: travis_on_the_host != "travis"

- name: Install oh-my-zsh TRAVIS STYLE
  shell: curl -fslL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
  # become: yes
  # become_method: sudo
  # when: travis_on_the_host == "travis"

