- name: Install vtop node.js package globally.
  npm:
    name: vtop 
    global: yes

- name: Exercism 
  raw: curl -fsSL https://raw.githubusercontent.com/exercism/cli-www/master/public/install | bash 

- name: FZF - Clone github repository to `$HOME/.fzf`
  git: repo=https://github.com/junegunn/fzf.git 
       dest=~/.fzf

- name: FZF - Run install script from cloned repository.
  shell: ~/.fzf/install --all
  register: fzf_install
  changed_when: "fzf_install.stdout | search('Added')"

- name: Antigen - Clone github repository to `$HOME/.antigen`
  git:
    repo=https://github.com/zsh-users/antigen
    dest=~/.antigen

- name: TPM - Clone github repository to `$HOME/.tmux/plugins/tpm`
  git:
    repo=https://github.com/tmux-plugins/tpm
    dest=~/.tmux/plugins/tpm

- name: Z - Clone github repository to `$HOME/.z`
  git:
    repo=https://github.com/rupa/z
    dest=~/.z

- name: Z - create .zdata
  file:
    path: ~/.zdata
    state: touch
    mode: "u=rw,g=r,o=r"
