---

- name: ANTIGEN - Clone github repository to `$HOME/.antigen`
  git:
    repo=https://github.com/zsh-users/antigen
    dest=~/.antigen

- name: ANTIGEN - Run update
  shell: "zsh -l -c -i 'antigen update'"
  register: antigen_update
  changed_when: FALSE

- debug: msg="{{ antigen_update.stdout }}"

