---

- name: NETCAT - Ubuntu - Install netcat with Apt
  become: yes
  become_method: 'sudo'
  apt: name=netcat state=latest update_cache=yes cache_valid_time=43200
  when: ansible_distribution == 'Ubuntu'

- name: NETCAT - MacOSX - Install netcat with Homebrew
  homebrew: name=netcat
    state=present
  when: ansible_distribution == 'MacOSX'
