---

- name: NODE - Ubuntu - Install node with Apt
  become: yes
  become_method: 'sudo'
  apt: name=node state=latest update_cache=yes cache_valid_time=43200
  when: ansible_distribution == 'Ubuntu'

- name: NODE - MacOSX - Install npm with Homebrew
  homebrew: name=npm
    state=present
  when: ansible_distribution == 'MacOSX'
