---
sudo: required
dist: trusty
os:
  - linux
  - osx
install:
  - curl -fsSL https://raw.githubusercontent.com/evangoad/devenv/master/install.sh | bash
script:
  - 'devenv -h'
  - 'devenv -l'
  - 'devenv -sl'
  - 'devenv -l --tags dotfiles'
  - 'devenv -l --tags shell'
  - 'devenv -l --tags editor'
  - 'devenv -l --tags mux'
  - 'devenv -l --tags dotfiles, mux'
