---

language: python
python: '2.7'

os:
  - linux
  - osx

# virtualenv:
#   system_site_packages: True

before_install: True
install: True

script:
  - 'curl -fsSL https://raw.githubusercontent.com/evangoad/devie/master/install.sh | bash'
  - 'ls -la $HOME'
  - 'devie-dev'
  # - 'git clone --depth 1 https://github.com/nickjj/rolespec'
  # - 'cd rolespec; bin/rolespec -r https://github.com/evangoad/devie'
