---
sudo: required
dist: trusty
os:
  - linux
  - osx
install:
  - bash install.sh
script:
  - 'devenv -h'
  - 'devenv -l'
  - 'devenv -sl'
  - 'devenv -l -t dotfile'
  - 'devenv -l -t shell'
  - 'devenv -l -t editor'
  - 'devenv -l -t mux'
  - "devenv -l -t 'dotfile, mux'"
