---
sudo: required
dist: trusty
os:
  - linux
  - osx
install:
  - curl -fsSL https://raw.githubusercontent.com/evangoad/devenv/master/install.sh | bash
before_script:
  - rm -rf ~/.rbenv
script:
  - 'devenv -h'
  - 'devenv -l'
  - 'devenv -sl'
  - 'devenv -l -t dotfile'
  - 'devenv -l -t shell'
  - 'devenv -l -t editor'
  - 'devenv -l -t mux'
  - "devenv -l -t 'dotfile, mux'"
