---
sudo: required
dist: trusty
os:
  - linux
  - osx
install:
  - curl -fsSL https://raw.githubusercontent.com/evangoad/devenv/master/install.sh | bash
script:
  - 'devenv --version'
  - 'devenv -h'
  - 'devenv -s'
  - > 
    devenv -l |
    grep -q 'failed=0'
    && (echo 'No Failures' && exit 0)
    || (echo 'Failures Detected' && exit 1)
  - >
    devenv -l |
    grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
