---
sudo: required
dist: trusty
os:
  - linux
  - osx
install:
  - curl -fsSL https://raw.githubusercontent.com/evangoad/devenv/master/install.sh | bash
script:
  - 'devenv --version'
  - 'devenv -h'
  - 'devenv'
  - 'devenv'

