#!/usr/bin/env bash
#
# devie tool for running install scripts and maintaining dotfiles

function output_version(){
  echo "devie 0.0.1"
}

function output_usage(){
  cat text/usage.txt 
}

while getopts "labcougrh" opt; do
  case $opt in
    l)
      yes O | eval $DEVIE_PATH/script/dotfile-link;;
    a)
      eval $DEVIE_PATH/install/archlinux/archlinux;;
    b)
      eval $DEVIE_PATH/install/babun/pact;;
    c)
      eval $DEVIE_PATH/install/cygwin/cygwin;;
    o)
      eval $DEVIE_PATH/install/osx/osx;;
    u)
      eval $DEVIE_PATH/install/ubuntu/ubuntu;;
    g)
      eval $DEVIE_PATH/script/gitenv;;
    r)
      eval $DEVIE_PATH/script/reload-shell;;
    h)
      output_usage;;
    \?)
      echo "Invalid option: $OPTARG" >&2
      exit 1
      ;;
  esac
done

exit 0
