#!/usr/bin/env bash
#
# devie tool for running install scripts and maintaining dotfiles

function output_version(){
  echo "devie 0.0.1"
}

function output_usage(){
  output_version
echo "usage: devie <commands>"
echo " " 
echo "commands:"
echo "  -l, link        symlinks dotfiles to $HOME"
echo "  -a, archlinux   runs 'pacman' and 'yaourt' scripts."
echo "  -b, babun       runs 'pact' scripts."
echo "  -c, cygwin      runs 'apt-cyg' and 'choco' scripts."
echo "  -o, osx         runs 'brew' and 'brew-cask' scripts."
echo "  -u, ubuntu      runs 'apt-get' scripts."
echo "  -g, gitenv      create .gitenv in $HOME, git credentials for writing commits."
echo "  -r, reload      detect shell, (sh, bash, or zsh) and reload correct dotfile."
}

while getopts "labcougrh" opt; do
  case $opt in
    l)
      yes O | eval $DEVIE_PATH/script/dotfile-link;;
    a)
      eval $DEVIE_PATH/install/archlinux/archlinux;;
    b)
      eval $DEVIE_PATH/install/babun/pact;;
    c)
      eval $DEVIE_PATH/install/cygwin/cygwin;;
    o)
      eval $DEVIE_PATH/install/osx/osx;;
    u)
      eval $DEVIE_PATH/install/ubuntu/ubuntu;;
    g)
      eval $DEVIE_PATH/script/gitenv;;
    r)
      eval $DEVIE_PATH/script/reload-shell;;
    h)
      output_usage;;
    \?)
      echo "Invalid option: $OPTARG" >&2
      exit 1
      ;;
  esac
done

exit 0
