- name: Symlink dotfiles
  copy: src={{ item }}
        dest=~/.{{ item }}
  with_items:
    - vimrc
    - zshrc
    - tmux.conf
    - gitconfig
    - hgrc
    - profile

- name: Symlink vim configs
  copy: src=vim/{{ item }}.vim
        dest=~/.vim/{{ item }}.vim
  with_items:
    - fzf
