---

- name: Install libraries with Apt
  become: yes
  become_method: 'sudo'
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - vim
    - zsh
    - tmux
    - tree
    - silversearcher-ag
    - keychain
  register: installation

