#!/usr/bin/env bash
#
# archlinux, runs package manager scripts, unixlike, and forces zsh

eval $DEVIE_PATH/install/archlinux/pacman
eval $DEVIE_PATH/install/archlinux/yaourt
eval $DEVIE_PATH/install/unixlike
eval $DEVIE_PATH/script/force_zsh

exit 0
