#antigen
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-completions
antigen theme cloud
antigen apply

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

export PATH="/usr/local/sbin:$PATH"

# exercism
export PATH="$HOME/.exercism:$PATH"

#rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if hash rbenv 2>/dev/null; then
  eval "$(rbenv init -)"
fi

#pyenv
if hash pyenv 2>/dev/null; then
  # eval "$(pyenv init -)"
fi

# go
export GOPATH="$HOME/go"
export PATH="$HOME/go/bin:$PATH"

# tmuxinator
export EDITOR="vim"

# heroku
export PATH="/usr/local/heroku/bin:$PATH"

# cabal
export PATH="$HOME/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.4/bin:$PATH"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -l -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Postgres.app on OSX
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"

# keychain
keychain $HOME/.ssh/id_rsa

# z
export _Z_DATA="$HOME/.zdata"
. ~/.z/z.sh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# alias
alias fit="git reset --hard"
alias peace="sudo poweroff"
alias be="bundle exec"
alias moo="bundle exec rake db:migrate"
alias gi="git"
alias t="git status"
alias b="bundle"
alias z!="source ~/.zshrc"
alias v="vagrant"
alias booya="vagrant up && vagrant ssh"

autoload bashcompinit
bashcompinit


