---

- name: TMUX - Ubuntu - Install tmux with Apt
  become: yes
  become_method: 'sudo'
  apt: name=tmux state=latest update_cache=yes cache_valid_time=43200
  when: ansible_distribution == 'Ubuntu'

- name: TMUX - MacOSX - Install tmux with Homebrew
  homebrew: name=tmux
    state=present
  when: ansible_distribution == 'MacOSX'

- name: TMUX - Symlink tmux.conf
  file:
    src: ~/.devenv/roles/mux/files/tmux.conf
    dest: ~/.tmux.conf
    state: link
    force: true
  tags:
    - dotfile

