#!/usr/bin/env bash
#
# force_zsh, for shells with chsh, force zsh to be default shell

if [ ! $SHELL = "/bin/zsh" ]; then
  echo "changing to zsh"
  sudo chsh $USER -s /bin/zsh
else
  echo "zsh already default shell"
fi

exit 0
