#!/usr/bin/env bash
#
# gitenv creates .gitenv file with git user's name and email.

if [ -f $HOME/.gitenv ]; then
  echo ".gitenv already exists, logged in as"
  echo "$GIT_COMMITTER_EMAIL"
else
  read -p "Enter your name:" line </dev/tty
  GIT_COMMITTER_NAME=$line
  GIT_AUTHOR_NAME=$line
  read -p "Enter your email:" line </dev/tty
  GIT_COMMITTER_EMAIL=$line
  GIT_AUTHOR_EMAIL=$line
  echo "export GIT_COMMITTER_NAME='$GIT_COMMITTER_NAME'" >> $HOME/.gitenv
  echo "export GIT_COMMITTER_EMAIL='$GIT_COMMITTER_EMAIL'" >> $HOME/.gitenv
  echo "export GIT_AUTHOR_NAME='$GIT_AUTHOR_NAME'" >> $HOME/.gitenv
  echo "export GIT_AUTHOR_EMAIL='$GIT_AUTHOR_EMAIL'" >> $HOME/.gitenv
  echo "Logged in!"
fi

exit 0
