#!/usr/bin/env bash
#
# unixlike installs tools that work the same across all unix likes 

if [ -d "$HOME/.vim/bundle" ]; then
  echo "vundle already installed."
else
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

yes | vim +PluginInstall +qall now

if [ -d "$HOME/.oh-my-zsh" ]; then
  echo "oh-my-zsh already installed."
else
  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

if [ -d "$HOME/.fzf" ]; then
  echo "fzf already installed."
else
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  printf 'y\ny' | ~/.fzf/install 
fi

if [ -d "$HOME/.exercism" ]; then
  echo "exercism already installed."
else
  curl -o $HOME/exercism_install https://raw.githubusercontent.com/exercism/cli-www/master/public/install 
  chmod 705 $HOME/exercism_install
  eval $HOME/exercism_install $HOME/.exercism
  rm $HOME/exercism_install
fi

exit 0
