#!/usr/bin/env bash
#
# brew installs the brew package manager and package list.

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install zsh tmux vim the_silver_searcher npm elixir rust ghc cabal-install 

exit 0
