---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - vim
    - zsh
    - tmux
    - tree 
    - ag
    - fzf

- name: Cleanup Brew packages
  command: brew cleanup
