---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - git
    - vim
    - zsh
    - tmux
    - tree 
    - ag

- name: Create Screenshot Directory
  file: path=~/Pictures/Screenshots state=directory mode=0755

- name: Write to screencapture defaults
  raw: defaults write com.apple.screencapture location ~/Pictures/Screenshots

- name: Disable Autocorrect
  osx_defaults: 
    domain=NSGlobalDomain
    key=NSAutomaticSpellingCorrectionEnabled
    value=0

# as suggested by http://osxdaily.com/2011/01/26/change-the-screenshot-save-file-location-in-mac-os-x/
- name: Kill SystemUIServer
  raw: killall SystemUIServer

