---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - git
    - vim
    - zsh
    - tmux
    - tree 
    - ag

- name: Cleanup Brew packages
  command: brew cleanup

