#!/usr/bin/env bash
#
# choco installs choco package manager and package list 

if [ -z "$(type choco)" ]; then
  powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" 
else
  echo "chocolately already installed"
fi

choco install -y chocolatey googlechrome virtualbox autohotkey.install

exit 0
