---
- import_tasks: chrome.yml
  when: ansible_distribution == 'MacOSX'

- import_tasks: iterm.yml
  when: ansible_distribution == 'MacOSX'

- import_tasks: licecap.yml
  when: ansible_distribution == 'MacOSX'

- import_tasks: sequelpro.yml
  when: ansible_distribution == 'MacOSX'

- name: Create Screenshot Directory
  file: path=~/Pictures/Screenshots state=directory mode=0755
  when: ansible_distribution == 'MacOSX'

- name: Write to screencapture defaults
  raw: defaults write com.apple.screencapture location ~/Pictures/Screenshots
  when: ansible_distribution == 'MacOSX'

# as suggested by http://osxdaily.com/2011/01/26/change-the-screenshot-save-file-location-in-mac-os-x/
- name: Kill SystemUIServer
  raw: killall SystemUIServer
  when: ansible_distribution == 'MacOSX'

